### ISSUE TITLE
Proton AppImage

### ISSUE THREAD

**Issue by philipzae** [mmtrt/Wine-AppImage_old#2]
Would be good if you also build a proton build with dxvk. Here are some useful links.

Proton builds with dxvk
https://github.com/GloriousEggroll/proton-ge-custom

PlayOnLinux builds
https://www.playonlinux.com/wine/binaries/phoenicis/proton-linux-x86/
https://www.playonlinux.com/wine/binaries/phoenicis/proton-linux-amd64/

AppImage build attempted by @probonopd
https://github.com/probonopd/libhookexecv/tree/proton
https://github.com/probonopd/libhookexecv/issues/8

**Comment by mmtrt** [comment]
I could create it but wine appimage having private `amd64` creating issues with system libs currently being broken so for this idea to take shape it appimage would have to be working multiarch one as currently we have working 32bit version successfully still some issues here and there.
