### ISSUE TITLE
Can't use the archlinux lol-appimage on arch (ELFCLASS64)

### ISSUE THREAD

**Issue by NotAkitake** [mmtrt/Wine-AppImage_old#3]
> /usr/lib32/../bin/wineserver: error while loading shared libraries: /usr/lib32/../bin/wineserver: wrong ELF class: ELFCLASS64

Am using the archlinux lol-patched appimage, doesn't work on my arch install for some reason.
The bionic one does though? Somehow?

**Comment by mmtrt** [comment]
Hmmm I've just tested archlinux version on Manjaro and bionic working fine.

When you get that error?

**Comment by NotAkitake** [comment]
When launching the game. And then it instantly quits.
On vanilla arch that is.

EDIT: Nevermind, I had my game symlinked to another drive, and was pointing to the symlink, which apparently works with the bionic appimage but not the arch one. I pointed to the game directly instead and it seems to work.
