### ISSUE TITLE
D9VK Arch Version /usr/lib32/../bin/wineserver Error (ELFCLASS64)

### ISSUE THREAD

**Issue by phaitonican** [mmtrt/Wine-AppImage_old#5]
Tried: https://github.com/mmtrt/Wine_Appimage/releases Arch Linux Version.
The arch linux AppImage gives me a different error:
`/usr/lib32/../bin/wineserver: error while loading shared libraries: /usr/lib32/../bin/wineserver: wrong ELF class: ELFCLASS64`

System Info:
Radeon RX 570
AMD Ryzen 5 2600x

**Comment by phaitonican** [comment]
nvm tried experimental build on lutris works fine now

**Comment by mmtrt** [comment]
can you try AppImage from continuous tag from todays build see if that fixes these errors.

**Comment by phaitonican** [comment]
yes, the non-arch continuous works now on my arch, but the other one still gives the same error. thank you :) I close the other issue with the bionic one and this one too because the arch AppImage is still experimental?
Thanks very much

**Comment by phaitonican** [comment]
sorry, I forgot to install D9VK dlls. Still getting the same error with Arch AppImage.
