### ISSUE TITLE
D9VK Issue

### ISSUE THREAD

**Issue by phaitonican** [mmtrt/Wine-AppImage_old#6]
Getting this error with the bionic AppImage and D9VK dll's.
Maybe I am doing something wrong?
Error:
```
info:  DXVK: d9vk-0.12
warn:  OpenVR: Failed to locate module
info:  Required Vulkan extension VK_KHR_get_physical_device_properties2 not supported
info:  Required Vulkan extension VK_KHR_surface not supported
info:  Required Vulkan extension VK_KHR_win32_surface not supported
terminate called after throwing an instance of 'dxvk::DxvkError'
```
System:
Arch Linux
AMD RX 570
AMD Ryzen 5 2600x

**Comment by phaitonican** [comment]
extensions seem missing for my actually supported graphics card. I think this is not the issue of the AppImage or anything rather a mesa issue or something IDK. still thanks

**Comment by mmtrt** [comment]
You are using these appimages with lutris right? If yes then make sure disable lutris icd file from lutris as appimages from continuous use icd from appimage.

**Comment by phaitonican** [comment]
yes. I tried every possibility, disabled ICD loader (because you said its now included in the AppImage itself), enabled 32 bit, enabled 64 bit, disabled again... I see some other people have this issue with other games, so I think this is rather a bug of vulkan or maybe my graphics card is too old but actually rx570 should be supported looking on this page: https://en.wikipedia.org/wiki/Vulkan_(API)#Compatibility
Still thanks for help

**Comment by mmtrt** [comment]
Do you have drivers installed for both arch https://github.com/lutris/lutris/wiki/Installing-drivers#installing-vulkan

**Comment by mmtrt** [comment]
Also can you provide output of this
`cat /var/log/Xorg.0.log | grep -e "DRI driver:" | awk '{print $8}'`

**Comment by phaitonican** [comment]
Yes. For both, 32 and 64 bit. Also reinstalled again to be 100% sure...

Output
`radeonsi`

Seems I have Souther Islands graphicscard.
I read something about this to set up this might be the issue thank you very much :)

**Comment by phaitonican** [comment]
got it!

**Comment by phaitonican** [comment]
Updated comment

**Comment by mmtrt** [comment]
If it output correctly then now try launching with lutris icd disabled

**Comment by phaitonican** [comment]
icd disabled and continuous build
set radeon.si_support=0 amdgpu.si_support=1 from https://wiki.archlinux.org/index.php/AMDGPU#Enable_Southern_Islands_(SI)_and_Sea_Islands_(CIK)_support
same error :( sorry this is not your AppImages fault rather my cards

**Comment by mmtrt** [comment]
Yea but that could be due to appimage not supporting amdgpu drivers but only supporting radv. Though I'm not sure about that issue.

**Comment by phaitonican** [comment]
I am not sure if this is the AppImage fault because some other have this same issue with other games for example:
https://forums.lutris.net/t/eso-poe-dxvk-missing-vulkan-extensions-which-are-actually-supported/4437
So maybe a vulkan issue..
Still thank you for your effort.

**Comment by phaitonican** [comment]
Hmm it seems maybe the AppImage is broken on my end or maybe Lutris makes some of my environment variables wrong...
Seems like it's neither a DXVK nor a Vulkan issue :(

**Comment by mmtrt** [comment]
Try appimage directly without lutris see if that fixes this issue.

**Comment by phaitonican** [comment]
tried with no luck :/ same issue..
it seems to be somewhat on my end, but I completely reinstalled my arch and `vulkaninfo` actually works so I'm not sure what I am doing wrong. Maybe it really is a Vulkan bug or something

**Comment by phaitonican** [comment]
It seems to be an error on the AppImage, because if I don't use the AppImage I get the launcher to work with D9VK, unfortunately I can't join a game because as you said we need new gcc which was provided in the AppImage. Still thanks for helping! (seems AppImage provides wrong icd loader) or something like that... (but it seems to work for other people IDK why not for me)

**Comment by mmtrt** [comment]
If you can use dxvk fine on system install wine without appimage or lutris then sure it can be issue with appimage. Still you can play game the with appimage without using  vulkan no dxvk installed which will work game with opengl.

**Comment by phaitonican** [comment]
yes game works without DXVK. Maybe I should use arch AppImage?
