### ISSUE TITLE
Hard coded wineprefix

### ISSUE THREAD

**Issue by smichel17** [mmtrt/Wine-AppImage_old#7]
Would it be possible to dynamically set the prefix based on the `WINEPREFIX` environment variable, rather than hard coding to `~/.wine-appimage-lol`?

For context, see the context section of https://github.com/lutris/lutris/pull/2244

Right now I'm working around it with a bash wrapper to symlink the hard coded prefix to the actual install location, but this is really a hack and brings its own set of issues.

**Comment by mmtrt** [comment]
can you try build from continuous release.

**Comment by smichel17** [comment]
Works! And defaults to `~/.wine` if undefined. I think it'd be reasonable to
```
export WINEPREFIX=${WINEPREFIX:-$HOME/.wine-appimage-lol}
```
It'd also be nice to do the same thing for `WINEDEBUG`, to help with getting logs when people are having trouble getting it to run.

**Comment by mmtrt** [comment]
Pushed some changes now it should be good though I've not tested these changes except `WINEPREFIX`  `WINEDEBUG`.

**Comment by smichel17** [comment]
Seems to work for me! Let me know when you're ready for the next release so I can update the Lutris installers to use the new builds :)

**Comment by mmtrt** [comment]
builds from continuous should be usable.

**Comment by smichel17** [comment]
Yeah, we decided to use it, but rehost it so we can link to a static file. Anyway, my issue is solved; you can close this issue or leave it open if you'd rather wait for a release. Thank you for the quick responses :)
