### ISSUE TITLE
debian buster ld-linux.so.2: No such file or directory

### ISSUE THREAD

**Issue by liuhoward** [mmtrt/Wine-AppImage_old#9]
Hi, I forked your code, and compiled debian buster with staging branch, the output AppImage's size is only about 50MB, when I execute it, it failed with "/tmp/.mount_wine-s7BHGZE/AppRun: line 82: /tmp/.mount_wine-s7BHGZE/lib/ld-linux.so.2: No such file or directory", anything wrong with my setting? thanks

**Comment by mmtrt** [comment]
extract your compiled appimg by this command.

./filenam.appimg --appimg-extract

check for that file there if it's on different folder then make changes to apprun file on repo.

**Comment by liuhoward** [comment]
OK, thanks, I will try.

**Comment by liuhoward** [comment]
extracted, there is no ld-linux.so.2 in all folders. and I compared it with bionic one, many sub-folders & files are missing in buster one. 
here is the compile log: https://travis-ci.org/liuhoward/Wine_Appimage/builds/624859173
thanks!

**Comment by liuhoward** [comment]
I found the reasons, some packages are missing in Debian, to fix it:
Debian buster (tested): libavcodec57 -> libavcodec58
Debian stretch (not tested): libva2 -> libva1, libva-drm2 -> libva-drm1, libva-x11-2 -> libva-x11-1
